[build]
  publish = "public"
  command = "./build.sh"

[build.environment]
  HUGO_VERSION = "0.126.1"

[context.production.environment]
  HUGO_ENV = "production"
  
[context.deploy-preview.environment]
  HUGO_ENV = "preview"

# Redirect default Netlify subdomain to primary domain
[[redirects]]
  from = "https://cosmic-life-search.netlify.app/*"
  to = "https://cosmiclifesearch.com/:splat"
  status = 301
  force = true

# Redirects and headers for all routes
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://www.google-analytics.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://www.google-analytics.com; connect-src 'self' https://www.google-analytics.com; font-src 'self'; object-src 'none'; form-action 'self' https://www.viator.com; frame-src 'self' https://www.youtube.com; navigate-to https://*.viator.com https://viator.com"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"